name: Publish to pypi.org

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          vault_instance: dev
          # Secrets placed in the ci/repo/grafana/otel-profiling-python/ path in Vault
          repo_secrets: |
            PYPI_API_TOKEN=publishing:pypi_api_key
      - uses: robinraju/release-downloader@v1.4
        with: 
          tag: ${{ github.event.release.tag_name }}
          fileName: "*"
          tarBall: false 
          zipBall: false 
          out-file-path: "dist"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ env.PYPI_API_TOKEN }}
